fsMZQ: 6KolQ # 対空射撃
fwHII: 6DH3S # 深き森の異形
fof0I: 61qeS # エンシェントエルフ
fskF2: 5-Hb2 # 抜刀する執行者　タージ
fsmhI: 6LCtI # ランサー
fwfio: 69rKo # レヴィオンセイバー・アルベール
f-Tro: 69rKo # レヴィオンセイバー・アルベール
fp1Qo: 62D2o # 海底都市王・乙姫
fx27I: 6E1uS # 魔導の巨兵
ft9qg: 6Lc0g # 精神統一
fpPrI: 62bTS # マーリン
f-sGI: 6ADlI # 次元の魔女・ドロシー
fxQXo: 6EQIo # 水竜神の巫女
fpoFo: 62zty # ダークドラグーン・フォルテ
ftZyY: 62xRs # ケイオスドラゴン　アジルス
f_Ego: 6Ac9o # インペリアルドラグーン・アルドス
ftahQ: 6M0tQ # 誓いの一撃
fxoyI: 6A-aI # ネフティス
fqAgI: 63MII # ケルベロス
fttUY: 6MJgY # セイバーオルタ
f_d5I: 63MII # ケルベロス
fuJ4A: 6MlGA # 絡み付く鎖
f_uB2: 5_pFg # ダークジェネラル・エクセラ
fyBMo: 6FB7o # ベルフェゴール
fqZ4o: 63kio # クイーンヴァンパイア
fqxVI: 6477c # ジャンヌダルク
fyZnI: 6FZYS # ヘヴンリーイージス
fuglo: 6N6y6 # バーサーカー