fsMZQ: 6KolQ # 対空射撃
g1o-Q: 5zvvQ # 森荒らしへの報い
fof0I: 61qeS # エンシェントエルフ
f-5RI: 6OjUI # 導きの妖精姫・アリア
fwHII: 6DH3S # 深き森の異形
fskF2: 5-Hb2 # 抜刀する執行者　タージ
fsmhI: 6LCtI # ランサー
g2BOw: 5-IJw # 疾風怒濤
fwfio: 69rKo # レヴィオンセイバー・アルベール
f-Tro: 69rKo # レヴィオンセイバー・アルベール
fp1Qo: 62D2o # 海底都市王・乙姫
g2ZpQ: 5-gkQ # 知恵の光
ft9qg: 6Lc0g # 精神統一
fpPrI: 62bTS # マーリン
6W__a: 62Uta # 運命の導き
fx27I: 6E1uS # 魔導の巨兵
f-sGI: 6ADlI # 次元の魔女・ドロシー
g2yDw: 5_38w # 竜の託宣
ftahQ: 6M0tQ # 誓いの一撃
fxQXo: 6EQIo # 水竜神の巫女
ftZyY: 62xRs # ケイオスドラゴン　アジルス
fpoFo: 62zty # ダークドラグーン・フォルテ
f_Ego: 6Ac9o # インペリアルドラグーン・アルドス
6XmqQ: 63FiQ # ソウルコンバージョン
g3KeQ: 5_RZQ # 消えぬ怨恨
fqAgI: 63MII # ケルベロス
f_d5I: 63MII # ケルベロス
fttUY: 6MJgY # セイバーオルタ
fxoyI: 6A-aI # ネフティス
g3j34: 5_p-4 # 鋭利な一裂き
6UL5w: 63e74 # 眷属の召喚
fuJ4A: 6MlGA # 絡み付く鎖
f_uB2: 5_pFg # ダークジェネラル・エクセラ
fyBMo: 6FB7o # ベルフェゴール
fqZ4o: 63kio # クイーンヴァンパイア
g45TQ: 60COQ # 気高き教理
fuglo: 6N6y6 # バーサーカー
g0NwI: 6477S # ムーンアルミラージ・ラミナ
fqxVI: 6477c # ジャンヌダルク
fyZnI: 6FZYS # ヘヴンリーイージス
g4Ttw: 60aow # 次元断
g0mKo: 6RONy # 神秘の番人・スピネ