g96_Y: 6S6mi # 天界の尖兵
gSBiY: 6o_cY # 荒野の案内人
g97kQ: 6VxeQ # 熾天使の剣
gS7Yw: 6oxSw # 荒野の休息
lhupk: lhupa # 
gKa9Q: 6lCCQ # エンジェルシュート
gKZQY: 6hNKY # マシンエンジェル
6hhbQ: 61k2Q # 自然の導き
gH3YQ: 61k2Q # 自然の導き
6a3JQ: 61k32 # フェアリーサークル
6pJtQ: 6KolQ # 対空射撃
fsMZQ: 6KolQ # 対空射撃
gWMYg: 6tASg # スピリットシャイン
g1o-Q: 5zvvQ # 森荒らしへの報い
gDHrg: 6dvug # 強者の威風
gWMYq: 6-okg # 癒しの波動
fof0I: 61qeS # エンシェントエルフ
gOoQI: 6a9vc # 森の女王・リザ
gH3Ya: 6lVkQ # 豊穣の季節
gH5VQ: 6hjYQ # フォレスト・コア
f-5RI: 6OjUI # 導きの妖精姫・アリア
gaErI: 6pQTS # 回帰する抱擁・ラティカ
g5jjI: 6KvLI # カシオペア
rfm_m: 6tEcI # フォレストエース・リマーガ
fwHII: 6DH3S # 深き森の異形
fskF2: 5-Hb2 # 抜刀する執行者　タージ
g2BOw: 5-IJw # 疾風怒濤
gHUPK: 6lwbA # 優雅なもてなし
gWnPQ: 6_DbQ # 鎧袖一触
fsmhI: 6LCtI # ランサー
gDdpw: 6eFsw # 神速の歩法
gHUPA: 6i6SA # 白刃の剣舞
gHWrQ: 6pnAQ # 思わぬ躓き
lii5c: lii4- # 
gHTvw: 6i5yw # グローリー・コア
gWiWw: 6tWQw # 居合の真髄
fwfio: 69rKo # レヴィオンセイバー・アルベール
f-Tro: 69rKo # レヴィオンセイバー・アルベール
fp1Qo: 62D2o # 海底都市王・乙姫
g667o: 6P5uo # ダークセイバー・メリッサ
rg6-y: 6i89s # ミストデューク・アゾード
lii5m: lii58 # 
gPAqo: 6eMT6 # 舞い踊る刃・ディオネ
g2ZpQ: 5-gkQ # 知恵の光
6apfA: 66IXe # くず鉄の練成
6mG4A: 6HkyA # 魔女の大釜
gHqNk: 5-gka # マジックミサイル
gHqNa: 5-gku # ウィンドブラスト
gE0EQ: 6eeHQ # 魔術の一撃
6q6fQ: 6PPgQ # 静寂の実験室
gPWp2: 6ty_2 # 小さな優等生・キョウカ
ft9qg: 6Lc0g # 精神統一
gHsKQ: 6iUNQ # ウィズダム・コア
gHsKa: 6iUNQ # ウィズダム・コア
fpPrI: 62bTS # マーリン
g6UYI: 6Hs1I # オズの大魔女
6W__a: 62Uta # 運命の導き
gHqNQ: 62Uta # 運命の導き
fx27I: 6E1uS # 魔導の巨兵
rgVOq: 6_bHC # ドワーフの工房長
gX4xQ: 5-glM # 炎の握撃
f-sGI: 6ADlI # 次元の魔女・ドロシー
lj4Vy: lj4VK # 
gPZFI: 6awkI # 開闢の予言者・ティオ
rgtp0: 6_zhi # エターナルホエール
gXTLw: 6uHFw # 武力炎翔
rgs5e: 73m7A # 竜の助言
g6syo: 6Tgt6 # 銀氷のドラゴニュート・フィルレイン
g2yDw: 5_38w # 竜の託宣
gETXQ: 6f5aQ # 力の鍛造
ftahQ: 6M0tQ # 誓いの一撃
gIEkw: 6isnw # ドラゴニック・コア
gbO4o: 6qZiy # 呪われし影・ヴァイディ
gICnw: 6iqqw # 圧倒する猛撃
fxQXo: 6EQIo # 水竜神の巫女
gPxfo: 6bJ8o # 侮蔑の絶傑・ガルミーユ
ftZyY: 62xRs # ケイオスドラゴン　アジルス
fpoFo: 62zty # ダークドラグーン・フォルテ
f_Ego: 6Ac9o # インペリアルドラグーン・アルドス
rgwF6: 6XU_o # 大いなる調停者・ゾーイ
gQHe2: 6ujq2 # プリンゴースト・ミヤコ
6XmqQ: 63FiQ # ソウルコンバージョン
g3KeQ: 5_RZQ # 消えぬ怨恨
gEn3Q: 6fP6Q # 悪意の憑依
gId9Q: 6jFCQ # ソウル・コア
gQK4I: 6jJrS # 紫紺の抵抗者・エンネア
g7FNI: 6n7-S # 冥守の頂点・アイシャ
mw4zC: mw4z2 # 
gXuCg: 6yWFg # フェイタルオーダー
fqAgI: 63MII # ケルベロス
f_d5I: 63MII # ケルベロス
fttUY: 6MJgY # セイバーオルタ
rhIgi: 6n7-I # 冥界神・ハデス
fxoyI: 6A-aI # ネフティス
rhIhK: 6yaPS # デッドメタルスター
gQiUo: 6jiFy # 真紅の抗戦者・モノ
g3j34: 5_p-4 # 鋭利な一裂き
6UL5w: 63e74 # 眷属の召喚
fuJ4A: 6MlGA # 絡み付く鎖
gIzcw: 6nPow # 魅惑の一撃
rhh4Q: 6rKY6 # クドラク
gFEMQ: 6fsPQ # 理性の崩壊
gI_Zw: 6jdcw # ブラッド・コア
f_uB2: 5_pFg # ダークジェネラル・エクセラ
fyBMo: 6FB7o # ベルフェゴール
g7dno: 6MpPo # 毒牙の姫・メドゥーサ
rhh4a: 70myo # 《節制》・ルーゼン
gYGdA: 70ipA # 燃え盛る抵抗
fqZ4o: 63kio # クイーンヴァンパイア
gYhEI: 6nssI # 黄金の鐘
g45TQ: 60COQ # 気高き教理
gYcbQ: 60COa # 漆黒の法典
gJN-Q: 6k01Q # セイント・コア
gFcmw: 6gEpw # 射殺す輝き
fuglo: 6N6y6 # バーサーカー
g0NwI: 6477S # ムーンアルミラージ・ラミナ
g80CI: 6Uq6I # 神の盾・ブローディア
fqxVI: 6477c # ジャンヌダルク
gR4vI: 6cSOI # 輝く熾天使・ラピス
fyZnI: 6FZYS # ヘヴンリーイージス
gY-_w: 6vovw # コンセントレイト
gZ1SK: 71TeA # アーティファクトスキャン
gFwIw: 6gYLw # 破壊の愉悦
gJpKQ: 6kRNQ # 機構の解放
gZ1SA: 6oD4A # 構造の解析
g4Ttw: 60aow # 次元断
gJpKa: 6s3fQ # アーティファクトコール
gJmOw: 6kORw # オリジン・コア
gRTJo: 6cqoo # 破壊の絶傑・リーシェナ
g0mKo: 6RONy # 神秘の番人・スピネ
g8Oco: 6VCWo # 人形の少女・オーキス