---
- clan_id: 1
  name: 冥府E
  detection_order: 1
  conditions:
  - 61QWQ: 2 # 新たなる運命
    61Q1A: 2 # 冥府への道
- clan_id: 1
  name: ニュートE
  detection_order: 2
  conditions:
  - 6GgLs: 2 # ヘクトル
- clan_id: 1
  name: 白狼E
  detection_order: 3
  conditions:
  - 69SwI: 1 # 白狼
    6KvLS: 1 # キングエレファント
- clan_id: 1
  name: アグロE
  detection_order: 4
  conditions:
  - 5zWm2: 3 # ゴブリン
    6KrBg: 2 # 妖精の調べ
- clan_id: 1
  name: OTKE
  detection_order: 5
  conditions:
  - 61oCC: 3 # リノセウス
    68_dS: 2 # フィーナ
  - 61oCC: 3 # リノセウス
    6SQIs: 2 # バッタ
- clan_id: 1
  name: ミッドE
  detection_order: 6
  conditions:
  - 6DEdC: 2 # エリン
    6KvLI: 2 # カシオペア
- clan_id: 2
  name: ニュートR
  detection_order: 1
  conditions:
  - 68_dc: 3 # リリエル
- clan_id: 2
  name: アグロR
  detection_order: 2
  conditions:
  - 628BY: 3 # プリヴァン
  - 6LCtS: 3 # ジュリエット
    6LG2Q: 1 # 円卓会議
- clan_id: 2
  name: コンR
  detection_order: 3
  conditions:
  - 6DfTo: 1 # ローラン
- clan_id: 2
  name: ミッドR
  detection_order: 4
  conditions:
  - 6DabS: 1 # ルミナスメイジ
  - 6P5uy: 3 # アーサー
- clan_id: 3
  name: 力場W
  detection_order: 1
  conditions:
  - 62ZGg: 2 # 魔導の力場
- clan_id: 3
  name: 冥府W
  detection_order: 2
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 3
  name: ニュートW
  detection_order: 3
  conditions:
  - 6HkiY: 3 # スイーツウィッチ
- clan_id: 3
  name: 秘術W
  detection_order: 4
  conditions:
  - 6Dwa0: 3 # 天輪
  - 6A8t6: 3 # ドワーフアルケミスト
- clan_id: 3
  name: ドロシーW
  detection_order: 5
  conditions:
  - 6ADlI: 3 # ドロシー
- clan_id: 3
  name: 超越W
  detection_order: 6
  conditions:
  - 62Zm4: 2 # 超越
- clan_id: 4
  name: 原初D
  detection_order: 1
  conditions:
  - 6M2ao: 3 # 原初
- clan_id: 4
  name: OTKD
  detection_order: 2
  conditions:
  - 66giW: 3 # 竜少女
- clan_id: 4
  name: フェイスD
  detection_order: 3
  conditions:
  - 62sZ2: 3 # アイボリー
    62zty: 3 # フォルテ
- clan_id: 4
  name: ランプD
  detection_order: 4
  conditions:
  - 6EQIo: 3 # 水竜神の巫女
    694Vo: 2 # バハムート
  - 694Vy: 3 # サハクィエル
    6Cuey: 2 # イスラーフィール
- clan_id: 5
  name: 骸Nc
  detection_order: 1
  conditions:
  - 6KUzo: 2 # 階段
    63MIS: 2 # 骸
  - 6Q7pY: 2 # 陰鬱
    63MIS: 2 # 骸
- clan_id: 5
  name: リアニNc
  detection_order: 2
  conditions:
  - 6Cueo: 3 # ゼウス
    6QDQw: 2 # 生と死の逆転
- clan_id: 5
  name: ダリスNc
  detection_order: 3
  conditions:
  - 6CnpI: 2 # 力比べ
    6IcsI: 2 # ダークアリス
- clan_id: 5
  name: ネフNc
  detection_order: 4
  conditions:
  - 6A-aI: 3 # ネフティス
- clan_id: 5
  name: アグロNc
  detection_order: 5
  conditions:
  - 63Kaw: 2 # ハウル
    63MII: 3 # ケルベロス
- clan_id: 5
  name: ミッドNc
  detection_order: 6
  conditions:
  - 6EojS: 2 # ヘクター
    6EmHM: 1 # 不死の大王
  - 6EojS: 3 # ヘクター
- clan_id: 6
  name: ヨルムンV
  detection_order: 1
  conditions:
  - 6MkXc: 3 # デビルシープ
    6MpPy: 2 # ヨルムンガンド
- clan_id: 6
  name: ニュートV
  detection_order: 2
  conditions:
  - 6GgLs: 3 # ヘクトル
- clan_id: 6
  name: コンV
  detection_order: 3
  conditions:
  - 6F6kY: 2 # 黒死
    63i_a: 3 # 黙示録
  - 67SGY: 2 # 鮮血
    63i_a: 3 # 黙示録
- clan_id: 6
  name: 復讐V
  detection_order: 4
  conditions:
  - 6FB7o: 3 # ベルフェ
    6F6Fm: 2 # カオスシップ
  - 6FB7o: 3 # ベルフェ
    5_pFg: 2 # ダークジェネラル
  - 6FB7o: 3 # ベルフェ
    6QWE2: 2 # 硝子刃
  - 63kiy: 2 # ソウルディーラー
    5_pFg: 2 # ダークジェネラル
- clan_id: 6
  name: アグロV
  detection_order: 5
  conditions:
  - 67WPs: 3 # ヴァンピィ
  - 6UPFY: 2 # 血統の王
  - 5_p-4: 3 # 鋭利な一裂き
    63gZA: 2 # 夜の群れ
    6I_Go: 1 # カラボス
- clan_id: 7
  name: エイラB
  detection_order: 1
  conditions:
  - 67v3q: 3 # エイラ
- clan_id: 7
  name: 社B
  detection_order: 2
  conditions:
  - 6Unvg: 3 # 天狐の社
- clan_id: 7
  name: 邪教B
  detection_order: 3
  conditions:
  - 6NBqS: 3 # 邪教の権化
- clan_id: 7
  name: 教会B
  detection_order: 4
  conditions:
  - 6Qzmg: 3 # 教会
- clan_id: 7
  name: セラフB
  detection_order: 5
  conditions:
  - 67xlY: 2 # 熾天使
- clan_id: 7
  name: 疾走B
  detection_order: 6
  conditions:
  - 640IQ: 2 # 神鳥
    67uqM: 2 # ガルラ
- clan_id: 7
  name: イージスB
  detection_order: 7
  conditions:
  - 645Pw: 3 # テミス
    6FZYS: 1 # イージス
- clan_id: 8
  name: 冥府Nm
  detection_order: 1
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 8
  name: AFNm
  detection_order: 2
  conditions:
  - 6RHYc: 3 # 加速装置
    6ROO6: 3 # デウスエクスマキナ
- clan_id: 8
  name: 人形Nm
  detection_order: 3
  conditions:
  - 6VCWo: 1 # オーキス
- clan_id: 8
  name: ミッドNm
  detection_order: 4
  conditions:
  - 6RONy: 3 # スピネ
