---
- clan_id: 1
  name: フェアドラE
  detection_order: 1
  conditions:
  - 6H5CS: 3 # フェアリードラゴン
- clan_id: 1
  name: ニュートE
  detection_order: 2
  conditions:
  - 6GgLs: 2 # ヘクトル
  - 6H5CI: 3 # BB
    6H3Uw: 3 # 双撃
- clan_id: 1
  name: アグロE
  detection_order: 3
  conditions:
  - 6Ko0s: 2 # イピリア
    6KrBg: 2 # 妖精の調べ
  - 6D9l0: 2 # ビートルウォーリアー
    6KrBg: 2 # 妖精の調べ
- clan_id: 1
  name: コンE
  detection_order: 4
  conditions:
  - 6DEdM: 2 # ジャングル
    6KvLS: 2 # キングエレファント
  - 6KWwo: 1 # ロキ
    6KvLS: 1 # キングエレファント
- clan_id: 1
  name: ミッドE
  detection_order: 5
  conditions:
  - 6DEdC: 2 # エリン
    6KvLI: 2 # カシオペア
  - 6Ksv2: 2 # ヴィーナス
    6DEdC: 2 # エリン
  - 6Ksv2: 2 # ヴィーナス
    6KvLI: 2 # カシオペア
  - 6DEdC: 2 # エリン
    6SXdI: 2 # ユグドラシル
- clan_id: 2
  name: アグロR
  detection_order: 1
  conditions:
  - 6LG2Q: 1 # 円卓会議
    6HMI2: 2 # マスタークノイチ
  - 6DY9W: 1 # 旅ガエル
    6HMI2: 2 # マスタークノイチ
- clan_id: 2
  name: コンR
  detection_order: 2
  conditions:
  - 6DfTo: 2 # ローラン
  - 6DfTo: 1 # ローラン
    6P5uo: 1 # メリッサ
- clan_id: 2
  name: 援護射撃R
  detection_order: 3
  conditions:
  - 6DdHA: 2 # 援護射撃
- clan_id: 2
  name: ミッドR
  detection_order: 4
  conditions:
  - 6DabS: 2 # ルミナスメイジ
  - 6P5uy: 3 # アーサー
- clan_id: 3
  name: 秘術ジンジャーW
  detection_order: 1
  conditions:
  - 6E1uI: 2 # ジンジャー
    6Cueo: 2 # ゼウス
    6PPgQ: 2 # 静寂
- clan_id: 3
  name: NジンジャーW
  detection_order: 2
  conditions:
  - 6E1uI: 2 # ジンジャー
    6Cueo: 2 # ゼウス
- clan_id: 3
  name: ニュートW
  detection_order: 3
  conditions:
  - 6HkiY: 3 # スイーツウィッチ
- clan_id: 3
  name: 白銀剣W
  detection_order: 4
  conditions:
  - 6PUJS: 2 # 白銀剣のゴーレム
- clan_id: 3
  name: マナリアW
  detection_order: 5
  conditions:
  - 6PUJI: 3 # マナリア
    6TDZy: 3 # 竜術士
  - 6PUJI: 3 # マナリア
    6TBsQ: 3 # ストームレイジ
- clan_id: 3
  name: 秘術W
  detection_order: 6
  conditions:
  - 6HkyA: 2 # 大釜
  - 6PPgQ: 3 # 静寂
  - 6LbI6: 3 # フロウ
- clan_id: 3
  name: スペブW
  detection_order: 7
  conditions:
  - 6LgAS: 2 # ギガントキマイラ
  - 6TISS: 2 # 無貌の魔女
  - 5-iRo: 2 # フレイムデストロイヤー
- clan_id: 4
  name: リントD
  detection_order: 1
  conditions:
  - 6Tgsy: 2 # リントヴルム
- clan_id: 4
  name: ギルヴァD
  detection_order: 2
  conditions:
  - 6Tgso: 2 # ギルヴァ
- clan_id: 4
  name: 原初D
  detection_order: 3
  conditions:
  - 6M2ao: 3 # 原初
- clan_id: 4
  name: クロノスD
  detection_order: 4
  conditions:
  - 6OL3o: 2 # クロノス
- clan_id: 4
  name: フェイスD
  detection_order: 5
  conditions:
  - 5zWm2: 3 # ゴブリン
    6ENsi: 1 # アイナ
- clan_id: 4
  name: 無謀D
  detection_order: 6
  conditions:
  - 6ICFA: 2 # 無謀なる戦
- clan_id: 4
  name: ランプD
  detection_order: 7
  conditions:
  - 6EQIo: 3 # 水竜神の巫女
  - 6EQIo: 2 # 水竜神の巫女
    6Cueo: 2 # ゼウス
  - 6L-BY: 3 # 峡谷
- clan_id: 5
  name: ダリスNc
  detection_order: 1
  conditions:
  - 6IcsI: 2 # ダークアリス
- clan_id: 5
  name: リアニNc
  detection_order: 2
  conditions:
  - 6Cueo: 2 # ゼウス
    6QCi2: 2 # 死竜の使い手
  - 6Cueo: 2 # ゼウス
    6QDQw: 2 # 生と死の逆転
- clan_id: 5
  name: 最果てNc
  detection_order: 3
  conditions:
  - 6U3HS: 3 # 最果ての骸
- clan_id: 5
  name: ミッドNc
  detection_order: 4
  conditions:
  - 6EojS: 2 # ヘクター
    6QF8I: 1 # アイシャ
- clan_id: 6
  name: ヨルムンV
  detection_order: 1
  conditions:
  - 6MkXc: 2 # デビルシープ
    6MpPy: 2 # ヨルムンガンド
- clan_id: 6
  name: アグロV
  detection_order: 2
  conditions:
  - 5zWm2: 2 # ゴブリン
    5_pFW: 2 # インプランサー
  - 5zWm2: 2 # ゴブリン
    6I_Go: 2 # カラボス
- clan_id: 6
  name: 血統V
  detection_order: 3
  conditions:
  - 6UPFY: 2 # 血統の王
- clan_id: 6
  name: ニュートV
  detection_order: 4
  conditions:
  - 6GgLs: 3 # ヘクトル
  - 6Iyqi: 2 # ファントムキャット
    6Cpmm: 2 # 大梟
- clan_id: 6
  name: コンV
  detection_order: 5
  conditions:
  - 6F6kY: 2 # 黒死
    6IyqY: 2 # エメラダ
  - 6IwOc: 2 # バンダースナッチ
  - 6FB7y: 2 # メイルストロームサーペント
- clan_id: 6
  name: 復讐V
  detection_order: 6
  conditions:
  - 6FB7o: 2 # ベルフェ
    6F6Fm: 2 # カオスシップ
  - 6FB7o: 2 # ベルフェ
    5_pFg: 2 # ダークジェネラル
  - 6FB7o: 3 # ベルフェ
    6URhy: 2 # 闇喰らいの蝙蝠
- clan_id: 7
  name: 邪教B
  detection_order: 1
  conditions:
  - 6NBqS: 3 # 邪教の権化
- clan_id: 7
  name: 教会B
  detection_order: 2
  conditions:
  - 6Qzmg: 2 # 頂きの教会
    6Q_zS: 2 # ヘヴンリーナイト
- clan_id: 7
  name: 聖獅子B
  detection_order: 3
  conditions:
  - 6UjWQ: 3 # 聖獅子の結晶
- clan_id: 7
  name: 社B
  detection_order: 4
  conditions:
  - 6Unvg: 3 # 天狐の社
- clan_id: 7
  name: 獅子B
  detection_order: 5
  conditions:
  - 6JNhS: 2 # 黄金郷の獅子
- clan_id: 7
  name: イージスB
  detection_order: 6
  conditions:
  - 6FZYS: 1 # イージス
- clan_id: 7
  name: アミュB
  detection_order: 7
  conditions:
  - 6Uq6S: 3 # ケリュネイア
- clan_id: 8
  name: AFNm
  detection_order: 1
  conditions:
  - 6ROO6: 3 # デウスエクスマキナ
  - 6RHYc: 3 # 加速装置
  - 6ROO6: 2 # デウスエクスマキナ
    6RHYc: 1 # 加速装置
- clan_id: 8
  name: 人形Nm
  detection_order: 2
  conditions:
  - 6VCWo: 3 # オーキス
  - 6VCWo: 2 # オーキス
    6RJW4: 2 # ノア
- clan_id: 8
  name: ミッドNm
  detection_order: 3
  conditions:
  - 6RONy: 3 # スピネ
