---
- clan_id: 1
  name: 奥義E
  detection_order: 1
  conditions:
  - 76VAI: 2 # ソーン
    6tEcc: 2 # 妖精竜
- clan_id: 1
  name: アクセラE
  detection_order: 2
  conditions:
  - 6-suc: 2 # エリン
  - 72h1c: 2 # ルヴァン
    72fJw: 1 # 妖精の開花
- clan_id: 1
  name: ロキサスE
  detection_order: 3
  conditions:
  - 72h1S: 2 # ロキサス
- clan_id: 1
  name: 異形E
  detection_order: 4
  conditions:
  - 6-suS: 3 # 異形
- clan_id: 1
  name: ローフラE
  detection_order: 5
  conditions:
  - 6-suI: 3 # ローフラッド
    72h1S: 0 # ロキサス
    72Zis: 0 # サボテンカウボーイ
    72h1c: 0 # ルヴァン
- clan_id: 1
  name: 密林E
  detection_order: 6
  conditions:
  - 6t7HY: 3 # 守人
- clan_id: 1
  name: 機械E
  detection_order: 7
  conditions:
  - 6x2lS: 2 # ダミアン
- clan_id: 1
  name: アグロE
  detection_order: 8
  conditions:
  - 6t7Hs: 2 # ハンマーモンキー
- clan_id: 2
  name: 兵士R
  detection_order: 1
  conditions:
  - 733S6: 3 # ヴァルフリート
- clan_id: 2
  name: 連携R
  detection_order: 2
  conditions:
  - 6-UTy: 3 # フェイラン
  - 5-HbC: 2 # オースレスナイト
    6-UTy: 2 # フェイラン
- clan_id: 2
  name: 進化R
  detection_order: 3
  conditions:
  - 6tY8S: 2 # デュアルブレイダー
  - 6td16: 2 # アンリエット
  - 6-SmQ: 2 # 堕落の決意
  - 6_FIy: 2 # ダイヤモンドパラディン
  - 6_FJ6: 2 # アルヤスカ
  - 733Ry: 2 # ナハト・ナハト
- clan_id: 2
  name: 機械R
  detection_order: 4
  conditions:
  - 6xR9y: 3 # グレイソン
- clan_id: 2
  name: アグロR
  detection_order: 5
  conditions:
  - 5-KGw: 3 # 御旗
  - 72BIC: 3 # 自由なる冒険者
- clan_id: 2
  name: ミッドR
  detection_order: 6
  conditions:
  - 6xMHI: 3 # ゲルト
- clan_id: 3
  name: マイザーW
  detection_order: 1
  conditions:
  - 73RsI: 3 # マイザー
- clan_id: 3
  name: ヴィンセントW
  detection_order: 2
  conditions:
  - 73RsS: 1 # ヴィンセント
    73KXY: 3 # 保安官補
- clan_id: 3
  name: キャルW
  detection_order: 3
  conditions:
  - 6t_RS: 2 # キャル
    6t_RI: 0 # クオン
    6_djS: 0 # アダマンタイト
- clan_id: 3
  name: 機械W
  detection_order: 4
  conditions:
  - 6xpaS: 1 # レガロア
- clan_id: 3
  name: 秘術W
  detection_order: 5
  conditions:
  - 6_djS: 2 # アダマンタイト
  - 6_bH2: 2 # 魔導の君臨者
  - 6xkhy: 3 # 境界の魔道士
- clan_id: 3
  name: スペルW
  detection_order: 6
  conditions:
  - 5-iRo: 2 # フレイムデストロイヤー
  - 6t_RI: 2 # クオン
  - 6xpaI: 3 # ドロシー
  - 6_djc: 3 # ルーニィ
- clan_id: 4
  name: コンボD
  detection_order: 1
  conditions:
  - 77ePy: 3 # ディズレスタン
    73oZQ: 3 # 接近
- clan_id: 4
  name: ライドD
  detection_order: 2
  conditions:
  - 72BIC: 3 # 自由なる冒険者
    77bzY: 3 # ラスティナ
- clan_id: 4
  name: ホエールD
  detection_order: 3
  conditions:
  - 6_zhi: 1 # ホエール
    6yB-y: 0 # プレシオサウルス
  - 6_zhi: 1 # ホエール
    6_zhY: 3 # 虐殺のドラゴニュ＝と
- clan_id: 4
  name: ギルヴァD
  detection_order: 4
  conditions:
  - 6yB_6: 1 # ギルヴァ
    5_5bA: 3 # 灼熱の嵐
  - 6yB_6: 2 # ギルヴァ
    6yB-y: 0 # プレシオサウルス
- clan_id: 4
  name: ディスカD
  detection_order: 5
  conditions:
  - 6yB-y: 1 # プレシオサウルス
    7007y: 2 # 大逆
- clan_id: 4
  name: 機械D
  detection_order: 6
  conditions:
  - 6y76I: 2 # アマルガムドラゴン
- clan_id: 4
  name: ランプD
  detection_order: 7
  conditions:
  - 6yB-y: 2 # プレシオサウルス
  - 73qGy: 2 # レジー
  - 73qGo: 2 # 禁忌
  - 73qH6: 2 # ゲオルギウス
- clan_id: 5
  name: 奥義Nc
  detection_order: 1
  conditions:
  - 780qI: 2 # ニオ
    767Ug: 1 # 未来への飛翔
- clan_id: 5
  name: アグロNc
  detection_order: 2
  conditions:
  - 745MY: 3 # 恨みの語り部
  - 747oy: 3 # 暗がりの悪霊
  - 72BIC: 3 # 自由なる冒険者
- clan_id: 5
  name: ネフティスNc
  detection_order: 3
  conditions:
  - 70OYc: 3 # ネフティス
- clan_id: 5
  name: 葬送連携Nc
  detection_order: 4
  conditions:
  - 70OYI: 2 # ミルティオ
    6-UTy: 1 # フェイラン
    6uht2: 0 # 霊道
- clan_id: 5
  name: グレモリーNc
  detection_order: 5
  conditions:
  - 6yaPI: 1 # グレモリー
    74ChS: 2 # トリニティモンスターズ
- clan_id: 5
  name: 妖怪Nc
  detection_order: 6
  conditions:
  - 6umGI: 2 # ギンセツ
  - 6ujqC: 3 # 酒天童子
    70OYS: 0 # 征伐の死帝
- clan_id: 5
  name: 機械Nc
  detection_order: 7
  conditions:
  - 6yaPS: 3 # デッドメタルスター
    6umGI: 0 # ギンセツ
    70OYS: 0 # 征伐の死帝
- clan_id: 5
  name: コンNc
  detection_order: 8
  conditions:
  - 6yaPc: 2 # ナイトメアイーター
- clan_id: 6
  name: 碑文V
  detection_order: 1
  conditions:
  - 74Z8o: 2 # 碑文
    78PEy: 2 # ゼノ・ディアボロス
- clan_id: 6
  name: ボルテオV
  detection_order: 2
  conditions:
  - 74b5o: 3 # ボルテオ
- clan_id: 6
  name: バアルV
  detection_order: 3
  conditions:
  - 70mz6: 3 # バアル
    6ywNi: 3 # 背徳の狂獣
- clan_id: 6
  name: 狂乱V
  detection_order: 4
  conditions:
  - 70myy: 2 # ダルホード
  - 6v8h6: 3 # ベヒーモス
    70mz6: 0 # バアル
- clan_id: 6
  name: コンV
  detection_order: 5
  conditions:
  - 70myo: 3 # ルーゼン
  - 6-UTo: 2 # ゼルガネイア
- clan_id: 6
  name: ミッドV
  detection_order: 6
  conditions:
  - 6v8gy: 2 # イリヤ
    5_p-4: 2 # 鋭利な一裂き
  - 6ytxS: 2 # 凶槍の戦士
    5_p-4: 2 # 鋭利な一裂き
  - 6yypo: 2 # ネレイア
- clan_id: 6
  name: アグロV
  detection_order: 7
  conditions:
  - 5zWm2: 2 # ゴブリン
  - 72BIC: 3 # 自由なる冒険者
- clan_id: 7
  name: 西風神B
  detection_order: 1
  conditions:
  - 6vX5c: 3 # 西風神
- clan_id: 7
  name: セリーナB
  detection_order: 2
  conditions:
  - 74zWI: 3 # セリーナ
- clan_id: 7
  name: 清浄B
  detection_order: 3
  conditions:
  - 74xJg: 2 # 清浄の領域
- clan_id: 7
  name: サタンB
  detection_order: 4
  conditions:
  - 717QI: 1 # 邪教の神殿
    74zWI: 0 # セリーナ
- clan_id: 7
  name: 守護B
  detection_order: 5
  conditions:
  - 6vX5I: 3 # ウィルバート
- clan_id: 7
  name: カウントダウンB
  detection_order: 6
  conditions:
  - 6vPmi: 3 # カームフェザーフォルク
- clan_id: 7
  name: コンB
  detection_order: 7
  conditions:
  - 719Nc: 1 # ラー
- clan_id: 8
  name: 奥義Nm
  detection_order: 1
  conditions:
  - 79A3y: 2 # カトル
    79A3o: 2 # エッセル
- clan_id: 8
  name: 連携Nm
  detection_order: 2
  conditions:
  - 75Lwy: 2 # アイシィレンドリング
    6-UTy: 2 # フェイラン
- clan_id: 8
  name: コンNm
  detection_order: 3
  conditions:
  - 6vvVo: 3 # カルラ
  - 71Xny: 3 # ディメンションドミネーター
  - 71Xno: 3 # スロース
- clan_id: 8
  name: 機械Nm
  detection_order: 4
  conditions:
  - 6zjey: 3 # ベルフォメット
  - 6zjf6: 3 # マシンベア
- clan_id: 8
  name: AFNm
  detection_order: 5
  conditions:
  - 6vvW6: 2 # コロニー
  - 71TeA: 2 # スキャン
  - 75JUY: 2 # ジャスパー
- clan_id: 8
  name: 人形Nm
  detection_order: 6
  conditions:
  - 60dFA: 2 # 人形使いの糸
  - 6vr6Y: 3 # パペットボックス
  - 75EcC: 3 # ストリングマイスター
