---
- clan_id: 1
  name: ハイランダーE
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 1
  name: 冥府E
  detection_order: 2
  conditions:
  - 61QWQ: 2 # 新たなる運命
    61Q1A: 2 # 冥府への道
- clan_id: 1
  name: 白狼E
  detection_order: 3
  conditions:
  - 69SwI: 2 # 白狼
  - 69SwI: 1 # 白狼
    6a9vc: 3 # リザ
- clan_id: 1
  name: ニュートラルE
  detection_order: 4
  conditions:
  - 6H5CI: 3 # BB
  - 6GgLs: 2 # ヘクトル
  - 6CpmS: 3 # ゴブプリ
- clan_id: 1
  name: アグロE
  detection_order: 5
  conditions:
  - 5zWm2: 3 # ゴブリン
    6KrBg: 2 # 妖精の調べ
  - 5zvAY: 3 # ウォーターフェアリー
    6KrBg: 2 # 妖精の調べ
  - 5zWm2: 3 # ゴブリン
    659nE: 2 # 舞踏
- clan_id: 1
  name: コンボE
  detection_order: 6
  conditions:
  - 61oCC: 3 # リノセウス
    68_dS: 2 # フィーナ
  - 61oCC: 3 # リノセウス
    6SQno: 3 # 妖精花
  - 61oCC: 3 # リノセウス
    6OjUI: 2 # アリア
- clan_id: 1
  name: ミッドE
  detection_order: 7
  conditions:
  - 6DEdC: 2 # エリン
    6KvLI: 2 # カシオペア
  - 6DCB6: 2 # ヴィスト
    6a7T2: 3 # ベイル
  - 6DEdC: 2 # エリン
    6WJKC: 2 # メーテラ
  - 6SXdc: 2 # 翠嵐
  - 6dv9o: 2 # 森の戦士
- clan_id: 2
  name: ハイランダーR
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 2
  name: 冥府R
  detection_order: 2
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 2
  name: スパルタクスR
  detection_order: 3
  conditions:
  - 6Sw26: 1 # スパルタクス
    61QWQ: 3 # 新たなる運命
- clan_id: 2
  name: 兵士の誓いR
  detection_order: 4
  conditions:
  - 6eKGA: 2 # 兵士の誓い
- clan_id: 2
  name: 潜伏R
  detection_order: 5
  conditions:
  - 6DY9W: 3 # 旅ガエル
  - 628AS: 2 # アサシン
    628Ac: 3 # カースドジェネラル
  - 5-Hbq: 3 # クノイチエッグ
    6i3_w: 2 # 二刀流
- clan_id: 2
  name: 城塞R
  detection_order: 6
  conditions:
  - 628Pw: 3 # 城塞
- clan_id: 2
  name: アグロR
  detection_order: 7
  conditions:
  - 628BY: 3 # プリヴァン
  - 6LCtS: 3 # ジュリエット
    6LG2Q: 1 # 円卓会議
  - 6LFJi: 3 # ペルセウス
    625kg: 3 # ケンタウロスヴァンガード
- clan_id: 2
  name: コンR
  detection_order: 8
  conditions:
  - 6DfTo: 1 # ローラン
- clan_id: 2
  name: ミッドR
  detection_order: 9
  conditions:
  - 6DabS: 3 # ルミナスメイジ
  - 6P5uy: 3 # アーサー
  - 6aYJo: 3 # オクトリス
  - 6aVti: 3 # 簒奪の使徒
  - 6DfTy: 3 # ガウェイン
  - 62D2o: 3 # 乙姫
- clan_id: 3
  name: ハイランダーW
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 3
  name: 力場W
  detection_order: 2
  conditions:
  - 62ZGg: 2 # 魔導の力場
- clan_id: 3
  name: 冥府W
  detection_order: 3
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 3
  name: マナリアW
  detection_order: 4
  conditions:
  - 6auI2: 1 # アン
    6Hs1I: 2 # オズ
  - 6PUJI: 2 # 始祖マナリア
  - 6auI2: 2 # アン
    6X492: 2 # ミラ
  - 6auI2: 2 # アン
    6auIM: 2 # グレア
- clan_id: 3
  name: ニュートラルW
  detection_order: 5
  conditions:
  - 6HkiY: 3 # スイーツウィッチ
- clan_id: 3
  name: 秘術W
  detection_order: 6
  conditions:
  - 6Dz06: 2 # 奇術師
  - 6DwZs: 2 # 夜の魔術師
  - 6Dwa0: 2 # 天輪
  - 6HnOQ: 3 # お菓子の家
- clan_id: 3
  name: ドロシーW
  detection_order: 7
  conditions:
  - 6ADlI: 2 # ドロシー
    62Zm4: 0 # 超越
- clan_id: 3
  name: 超越W
  detection_order: 8
  conditions:
  - 62Zm4: 2 # 超越
- clan_id: 3
  name: スペルW
  detection_order: 9
  conditions:
  - 5-iRo: 3 # フレデス
  - 6edYi: 3 # 狂信者
- clan_id: 4
  name: ハイランダーD
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 4
  name: サタンD
  detection_order: 2
  conditions:
  - 6dbdo: 2 # サタン
  - 6dbdo: 1 # サタン
    6VwvY: 1 # ルリア
- clan_id: 4
  name: 庭園D
  detection_order: 3
  conditions:
  - 62xhK: 3 # 庭園
- clan_id: 4
  name: 原初D
  detection_order: 4
  conditions:
  - 6M2ao: 3 # 原初
- clan_id: 4
  name: 竜爪D
  detection_order: 5
  conditions:
  - 6AV4q: 2 # 竜爪
- clan_id: 4
  name: コンボD
  detection_order: 6
  conditions:
  - 66giW: 3 # 竜少女
- clan_id: 4
  name: アグロD
  detection_order: 7
  conditions:
  - 62sZ2: 3 # アイボリー
    62zty: 3 # フォルテ
  - 6bEGc: 3 # 侮蔑の信者
    62zty: 3 # フォルテ
  - 5zWm2: 3 # ゴブリン
    6bJ8o: 3 # ガルミーユ
  - 6AXHS: 3 # エイファ
- clan_id: 4
  name: ランプD
  detection_order: 8
  conditions:
  - 6EQIo: 3 # 水竜神の巫女
  - 694Vy: 2 # サハクィエル
    6Cuey: 2 # イスラーフィール
  - 66lqK: 2 # 連なる咆哮
  - 6IERy: 3 # ジャバウォック
  - 6bJ8o: 3 # ガルミーユ
- clan_id: 5
  name: ハイランダーNc
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 5
  name: アーカスNc
  detection_order: 2
  conditions:
  - 6U3Hc: 3 # アーカス
  - 6U3Hc: 2 # アーカス
    6Q8Io: 0 # スカルリング
- clan_id: 5
  name: 最果てNc
  detection_order: 3
  conditions:
  - 6U3HS: 3 # 最果ての骸
- clan_id: 5
  name: 骸Nc
  detection_order: 4
  conditions:
  - 63MIS: 3 # 骸
- clan_id: 5
  name: ネフティスNc
  detection_order: 5
  conditions:
  - 6A-aI: 3 # ネフティス
  - 6A-aI: 2 # ネフティス
    63Jsg: 2 # モルディカイ
- clan_id: 5
  name: リアニNc
  detection_order: 6
  conditions:
  - 63Jsg: 3 # モルディカイ
    6U0rC: 3 # 常闇の梟
  - "677_2": 3 # ケリドウェン
- clan_id: 5
  name: ダークアリスNc
  detection_order: 7
  conditions:
  - 6IcsI: 2 # ダークアリス
    6CnpI: 2 # 力比べ
  - 6IcsI: 2 # ダークアリス
    6EmmI: 2 # 手帳
- clan_id: 5
  name: 冥府Nc
  detection_order: 8
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 5
  name: タイラントNc
  detection_order: 9
  conditions:
  - 63JsW: 3 # デスタイラント
- clan_id: 5
  name: アグロNc
  detection_order: 10
  conditions:
  - 63Kaw: 2 # ハウル
    63MII: 3 # ケルベロス
  - 63Kaw: 2 # ハウル
    6GbT2: 2 # エフェメラ
- clan_id: 5
  name: ミッドNc
  detection_order: 11
  conditions:
  - 6EojS: 2 # ヘクター
  - 6bhZI: 2 # 冥界の番犬・ケルベロス
  - 6jJrI: 2 # 永遠の花嫁・セレス
- clan_id: 6
  name: ハイランダーV
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 6
  name: 機械V
  detection_order: 2
  conditions:
  - 6jiFy: 3 # モノ
- clan_id: 6
  name: バフ疾走V
  detection_order: 3
  conditions:
  - 6frgY: 2 # ピユラ
    6fmo2: 3 # フルフル
- clan_id: 6
  name: ヨルムンV
  detection_order: 4
  conditions:
  - 6MkXc: 3 # デビルシープ
    6MpPy: 2 # ヨルムンガンド
- clan_id: 6
  name: 自傷V
  detection_order: 5
  conditions:
  - 6c1Xi: 3 # フラウロス
  - 6c1Xi: 1 # フラウロス
    6c3zo: 2 # ヴァーナレク
  - 6URhy: 2 # 闇喰らいの蝙蝠
- clan_id: 6
  name: ニュートラルV
  detection_order: 6
  conditions:
  - 6GgLs: 3 # ヘクトル
- clan_id: 6
  name: コンV
  detection_order: 7
  conditions:
  - 6F6kY: 2 # 黒死
    63i_a: 2 # 黙示録
  - 67SGY: 2 # 鮮血の口付け
    63i_a: 2 # 黙示録
  - 6dbdo: 2 # サタン
    63i_a: 2 # 黙示録
- clan_id: 6
  name: 復讐V
  detection_order: 8
  conditions:
  - 6F6Fm: 3 # カオスシップ
  - 6FB7o: 3 # ベルフェ
    5_pFg: 2 # ダークジェネラル
  - 6frgi: 3 # ライカンベルセルク
- clan_id: 6
  name: アグロV
  detection_order: 9
  conditions:
  - 67WPs: 2 # ヴァンピィ
  - 6UPFY: 2 # 血統の王
  - 6Y8W2: 3 # 麗しのサキュバス
  - 5_p-4: 3 # 鋭利な一裂き
    63gZA: 2 # 夜の群れ
    6I_Go: 1 # カラボス
- clan_id: 7
  name: ハイランダーB
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 7
  name: 聖獣B
  detection_order: 2
  conditions:
  - 6gGXc: 2 # 楽園の聖獣
    6UjWQ: 0 # 聖獅子の結晶
    6Qzmg: 0 # 頂きの教会
- clan_id: 7
  name: ホーリーメイジB
  detection_order: 3
  conditions:
  - 642Fu: 3 # ホーリーメイジ
- clan_id: 7
  name: エイラB
  detection_order: 4
  conditions:
  - 67v3q: 3 # エイラ
- clan_id: 7
  name: 天狐B
  detection_order: 5
  conditions:
  - 6Unvg: 2 # 天狐の社
- clan_id: 7
  name: ニュートラルB
  detection_order: 6
  conditions:
  - 6JNhS: 2 # 黄金郷の獅子
  - 6GgLs: 2 # ヘクトル
- clan_id: 7
  name: カウントダウンB
  detection_order: 7
  conditions:
  - 6NBqS: 3 # 邪教の権化
  - 6YeFc: 2 # チェキババ
    67xlY: 0 # 熾天使
- clan_id: 7
  name: 陽光B
  detection_order: 8
  conditions:
  - 642UQ: 2 # 守護の陽光
- clan_id: 7
  name: 教会B
  detection_order: 9
  conditions:
  - 6Qzmg: 3 # 教会
- clan_id: 7
  name: 聖獅子B
  detection_order: 10
  conditions:
  - 6UjWQ: 3 # 聖獅子の結晶
- clan_id: 7
  name: セラフB
  detection_order: 11
  conditions:
  - 67xlY: 2 # 熾天使
  - 67xlY: 1 # 熾天使
    6cQBg: 1 # 黄金都市
- clan_id: 7
  name: 冥府B
  detection_order: 12
  conditions:
  - 61Q1A: 2 # 冥府への道
- clan_id: 7
  name: 疾走B
  detection_order: 13
  conditions:
  - 640IQ: 2 # 神鳥
    67uqM: 2 # ガルラ
  - 640IQ: 2 # 神鳥
    6cQBg: 1 # 黄金都市
- clan_id: 7
  name: コントロールB
  detection_order: 14
  conditions:
  - 6dbdo: 2 # サタン
  - 645Pw: 3 # テミス
- clan_id: 8
  name: ハイランダーNm
  detection_order: 1
  conditions:
  - 6ZnUo: 3 # マゼルベイン
- clan_id: 8
  name: サタンNm
  detection_order: 2
  conditions:
  - 6dbdo: 3 # サタン
  - 6dbdo: 2 # サタン
    6VwvY: 1 # ルリア
- clan_id: 8
  name: 球体Nm
  detection_order: 3
  conditions:
  - 6gfR2: 3 # 冒涜の球体
- clan_id: 8
  name: リーシェナNm
  detection_order: 4
  conditions:
  - 6cqoo: 3 # リーシェナ
    6ROO6: 0 # デウスエクスマキナ
- clan_id: 8
  name: CキャノンNm
  detection_order: 5
  conditions:
  - 6V7tw: 2 # クリスタルキャノン
- clan_id: 8
  name: AFNm
  detection_order: 6
  conditions:
  - 6ROO6: 3 # デウスエクスマキナ
  - 6RHYc: 3 # 加速装置
  - 6ROO6: 2 # デウスエクスマキナ
    6RHYc: 1 # 加速装置
  - 6gexo: 2 # ダイン
- clan_id: 8
  name: 人形Nm
  detection_order: 7
  conditions:
  - 6RJW4: 2 # ノア
  - 6VCWo: 3 # オーキス
  - 6gcVs: 3 # メイシア
    6ROO6: 0 # デウスエクスマキナ
    6cqoo: 0 # リーシェナ
- clan_id: 8
  name: アグロNm
  detection_order: 8
  conditions:
  - 5zWm2: 2 # ゴブリン
    6Z0fo: 3 # シルヴァ
- clan_id: 8
  name: ミッドNm
  detection_order: 9
  conditions:
  - 6RONy: 3 # スピネ
  - 6Z0fo: 3 # シルヴァ
