---
- clan_id: 1
  name: 密林E
  detection_order: 1
  conditions:
  - 6t7HY: 3 # 守人
  - 6tEcI: 3 # リマーガ
- clan_id: 1
  name: コンE
  detection_order: 2
  conditions:
  - 61k2Q: 2 # 自然の導き
    6hmTw: 2 # アリアの旋風
    6lZu2: 0 # 豪風のリノセウス
- clan_id: 1
  name: アマツE
  detection_order: 3
  conditions:
  - 6pQTI: 3 # アマツ
    6pQTS: 0 # ラティカ
- clan_id: 1
  name: 自然E
  detection_order: 4
  conditions:
  - 6pJ8s: 3 # スケアリートレント
    6lZu2: 0 # 豪風のリノセウス
- clan_id: 1
  name: 豪風リノE
  detection_order: 5
  conditions:
  - 6lZu2: 3 # 豪風のリノセウス
- clan_id: 1
  name: 機械E
  detection_order: 6
  conditions:
  - 6hoBS: 3 # クリフト
  - 6hgss: 3 # 機械ミノムシ
- clan_id: 1
  name: 進化E
  detection_order: 7
  conditions:
  - 6hPmy: 1 # オーディン
    6hoBI: 3 # シンシア
  - 6lDvy: 2 # ゼウス
  - 6lDvo: 2 # オリヴィエ
- clan_id: 1
  name: アグロE
  detection_order: 8
  conditions:
  - 6dxcM: 3 # リナ＆レナ
  - 6pLao: 3 # スピアーエルフ
  - 6t7Hs: 3 # ハンマーモンキー
- clan_id:
  name: ミッドE
  detection_order: 9
  conditions:
  - 6lcKI: 2 # オムニス
  - 6lcKS: 2 # ティスタ
- clan_id: 2
  name: 自然R
  detection_order: 1
  conditions:
  - 6poty: 3 # ベイリオン
  - 6phZM: 3 # ハルバードウルフ
- clan_id: 2
  name: レヴィオンR
  detection_order: 2
  conditions:
  - 6phZC: 2 # レヴィオンの探索者
  - 6ltQ2: 3 # ルネス
  - 6l-ky: 3 # アルベール
- clan_id: 2
  name: 進化R
  detection_order: 3
  conditions:
  - 6hISC: 2 # フニカル
    6hKuS: 3 # ヤヴンハール
  - 6tY8S: 2 # デュアルブレイダー
- clan_id: 2
  name: 潜伏R
  detection_order: 4
  conditions:
  - 6eK0Y: 3 # リオード
    6l--Q: 3 # 王城
  - 6ltQM: 2 # 旅ガエル
- clan_id: 2
  name: 兵士の誓いR
  detection_order: 5
  conditions:
  - 6eKGA: 2 # 兵士の誓い
- clan_id: 2
  name: 機械R
  detection_order: 6
  conditions:
  - 6i89Y: 3 # トランプルフォートレス
- clan_id: 2
  name: アグロR
  detection_order: 7
  conditions:
  - 5-Hb2: 3 # クイブレ
    5zWm2: 3 # ゴブリン
- clan_id: 2
  name: ミッドR
  detection_order: 8
  conditions:
  - 6iAbo: 3 # リーシャ
  - 6l-ko: 3 # アルビダ
- clan_id: 3
  name: 式神W
  detection_order: 1
  conditions:
  - 6t_RI: 2 # クオン
- clan_id: 3
  name: 専門店W
  detection_order: 2
  conditions:
  - 6q95g: 3 # 魔道具専門店
- clan_id: 3
  name: 自然W
  detection_order: 3
  conditions:
  - 6q8s2: 3 # ライリー
- clan_id: 3
  name: 進化W
  detection_order: 4
  conditions:
  - 6mN9I: 3 # ジンジャー
  - 6mN9I: 2 # ジンジャー
    6eiRC: 3 # モニカ
- clan_id: 3
  name: 機械W
  detection_order: 5
  conditions:
  - 6mIGy: 3 # マシンブックソーサラー
- clan_id: 3
  name: 秘術W
  detection_order: 6
  conditions:
  - 6ektI: 2 # 災厄獣
  - 6iZ0I: 3 # マギサ
  - 6mN9S: 2 # エラスムス
  - 6mKjC: 3 # レヴィ
- clan_id: 3
  name: スペルW
  detection_order: 7
  conditions:
  - 5-iRo: 2 # フレイムデストロイヤー
  - 6ektS: 2 # スウィート☆メドゥーサ
  - 6edYi: 3 # 真実の狂信者
  - 6iZ0c: 3 # ソロモン
  - 6mNuA: 2 # 究極練成
- clan_id: 4
  name: サタンD
  detection_order: 1
  conditions:
  - 6dbdo: 2 # サタン
- clan_id: 4
  name: 自然D
  detection_order: 2
  conditions:
  - 6qZiy: 2 # ヴァイディ
- clan_id: 4
  name: 進化D
  detection_order: 3
  conditions:
  - 6lDvy: 2 # ゼウス
  - 6lDvo: 2 # オリヴィエ
- clan_id: 4
  name: 財宝D
  detection_order: 4
  conditions:
  - 6mjco: 3 # 竜の財宝
- clan_id: 4
  name: アグロD
  detection_order: 5
  conditions:
  - 5zWm2: 3 # ゴブリン
    6qXGi: 3 # マリオン
  - 6iu-Y: 3 # 飛翔の竜人
  - 6meF2: 3 # ガジェットマーメイド
- clan_id: 4
  name: ランプD
  detection_order: 6
  conditions:
  - 6mlZo: 3 # ジェネシス
  - 6mla6: 2 # アイラ
- clan_id: 5
  name: 妖怪Nc
  detection_order: 1
  conditions:
  - 6umGI: 3 # ギンセツ
    6n7-I: 0 # ハデス
- clan_id: 5
  name: 自然Nc
  detection_order: 2
  conditions:
  - 6qy7I: 3 # ルベル
- clan_id: 5
  name: 冥府Nc
  detection_order: 3
  conditions:
  - 6n7-I: 3 # ハデス
- clan_id: 5
  name: 機械Nc
  detection_order: 4
  conditions:
  - 6jJrS: 3 # エンネア
- clan_id: 5
  name: 進化Nc
  detection_order: 5
  conditions:
  - 6hISC: 3 # フニカル
    6hKuS: 3 # ヤヴンハール
- clan_id: 5
  name: リアニNc
  detection_order: 6
  conditions:
  - 6fVic: 3 # タルタロス
    6n7-I: 0 # ハデス
- clan_id: 5
  name: サタンNc
  detection_order: 7
  conditions:
  - 6dbdo: 2 # サタン
- clan_id: 5
  name: アグロNc
  detection_order: 8
  conditions:
  - 5zWm2: 3 # ゴブリン
  - 6qvh2: 3 # ヘリオ
    6qy7S: 0 # トート
  - 6ujqC: 3 # 酒呑童子
    6umGI: 0 # ギンセツ
- clan_id: 5
  name: ミッドNc
  detection_order: 9
  conditions:
  - 6jJrI: 2 # セレス
- clan_id: 6
  name: 自傷V
  detection_order: 1
  conditions:
  - 6nR_Y: 3 # 加虐の独房
  - 6rI5s: 3 # バルト
  - 6rKY6: 3 # クドラク
    6rKXy: 0 # 胎動の魔神
- clan_id: 6
  name: 自然V
  detection_order: 2
  conditions:
  - 6rKXy: 2 # 胎動の魔神
- clan_id: 6
  name: 機械復讐V
  detection_order: 3
  conditions:
  - 6jiFy: 3 # モノ
    6nTyY: 2 # アザゼル
- clan_id: 6
  name: 機械V
  detection_order: 4
  conditions:
  - 6jiG6: 3 # スレイ
  - 6jiFy: 3 # モノ
    6jiG6: 2 # スレイ
  - 6jiFy: 3 # モノ
    6nTyY: 0 # アザゼル
- clan_id: 6
  name: 進化V
  detection_order: 5
  conditions:
  - 6hISC: 3 # フニカル
  - 6hISC: 2 # フニカル
    6lDvy: 1 # ゼウス
- clan_id: 6
  name: ローズクイーンV
  detection_order: 6
  conditions:
  - 6fu6y: 2 # ローズクイーン
- clan_id: 6
  name: アグロV
  detection_order: 7
  conditions:
  - 5zWm2: 2 # ゴブリン
    5_pFW: 2 # インプランサー
- clan_id: 6
  name: 復讐V
  detection_order: 8
  conditions:
  - 6fu76: 3 # ラウラ
  - 6frgi: 2 # ライカンベルセルク
  - 5_pFg: 3 # ダークジェネラル
  - 6nTyY: 3 # アザゼル
    6jiFy: 0 # モノ
- clan_id: 7
  name: サタンB
  detection_order: 1
  conditions:
  - 6dbdo: 2 # サタン
- clan_id: 7
  name: 守護B
  detection_order: 2
  conditions:
  - 6vX5I: 3 # ウィルバート
    6nupS: 0 # 清純なる祈り・エイラ
- clan_id: 7
  name: 自然B
  detection_order: 3
  conditions:
  - 6riyI: 3 # ミルフィ
    6nupS: 0 # 清純なる祈り・エイラ
  - 6rgWC: 3 # アニエス
    6nupS: 0 # 清純なる祈り・エイラ
- clan_id: 7
  name: エイラB
  detection_order: 4
  conditions:
  - 6nupS: 3 # 清純なる祈り・エイラ
- clan_id: 7
  name: 機械B
  detection_order: 5
  conditions:
  - 6k4gS: 3 # リモニウム
    6nupS: 0 # 清純なる祈り・エイラ
- clan_id: 7
  name: 聖獣B
  detection_order: 6
  conditions:
  - 6gGXc: 3 # 楽園の聖獣
    6rgWC: 0 # アニエス
- clan_id: 7
  name: カウントダウンB
  detection_order: 7
  conditions:
  - 6riyS: 3 # スフィンクス
- clan_id: 7
  name: ミッドB
  detection_order: 8
  conditions:
  - 6gGXS: 3 # ヘクター
- clan_id: 8
  name: PPNm
  detection_order: 1
  conditions:
  - 6vvVo: 3 # カルラ
    6kOCS: 0 # 加速兵
- clan_id: 8
  name: ラグナNm
  detection_order: 2
  conditions:
  - 6s65g: 3 # ラグナアウェイク
    6vvVo: 0 # カルラ
- clan_id: 8
  name: 自然Nm
  detection_order: 3
  conditions:
  - 6s5Mo: 2 # メタルゴリラ
    6kOCS: 0 # 加速兵
  - 6p22o: 2 # 母なる君
- clan_id: 8
  name: 機械Nm
  detection_order: 4
  conditions:
  - 6kT4o: 3 # グライアス
  - 6kT56: 3 # ベルフォメット
- clan_id: 8
  name: 球体Nm
  detection_order: 5
  conditions:
  - 6gfR2: 3 # 冒涜の球体
- clan_id: 8
  name: AFNm
  detection_order: 6
  conditions:
  - 6gexo: 2 # ダイン
  - 6kOCS: 3 # 加速兵
  - 6kT4y: 2 # シオン
- clan_id: 8
  name: 人形Nm
  detection_order: 7
  conditions:
  - 6oHE6: 3 # オーキス
  - 6vr6Y: 3 # パペットボックス
